# Generated by Django 4.2 on 2024-11-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("symbol", models.CharField(max_length=10, null=True)),
                ("conversion_rate", models.JSONField(null=True)),
            ],
        ),
    ]
