# Generated by Django 4.2 on 2024-11-18 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("currency", "0001_initial"),
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="split",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="expenses",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="currency.currency"
            ),
        ),
        migrations.AddField(
            model_name="expenses",
            name="paid_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses_paid_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
